server:
  port: 8081

spring:
  application:
    name: team-service

  datasource:
#    url: jdbc:mysql://localhost:3306/team_database
    url: jdbc:mysql://team-db:3306/team_database
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
